name: Build Battle-Tanks with Pygbag
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-pygbag:
    name: Sandy Inspires - Battle-Tanks Game
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      run: |
            echo "Attempting to install pygbag"
            python -m pip install pygbag
            echo "Successfully installed pygbag"
            echo "Attempting to build the game"
            python -m pygbag --build $GITHUB_WORKSPACE/client.py
            echo "Successfully build the game and complied to WebAssembly"

    - name : "Upload to GitHub pages branch gh-pages testing"
      uses: hug58/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: battle_tanks/build/web